### ISSUE TITLE
Invalid KV for strings containing '\n'.

### ISSUE THREAD

**Issue by Diegofac** [google-github-actions/actions-utils#10]
### TL;DR

When I pass a string as: 'PARAMETER_FOO=foo,\nPARAMETER_BAR=bar,\nPARAMETER_BAZ=baz'. Give the following error:
```
Failed to parse KEY=VALUE pair "": missing "="
```

### Expected behavior

['PARAMETER_FOO=foo', 'PARAMETER_BAR=bar', 'PARAMETER_BAZ=baz']

### Observed behavior

['PARAMETER_FOO=foo', '', 'PARAMETER_BAR=bar', '', 'PARAMETER_BAZ=baz']

### Action YAML

```yaml
- name: Deploy to Cloud Run
  id: deploy
  uses: google-github-actions/deploy-cloudrun@main
  with:
    service: my-service
    image: my-image:latest
    env_vars: |-
      PARAMETER_FOO=foo,
      PARAMETER_BAR=bar,
      PARAMETER_BAZ=baz
```

### Additional information

Looking at the code and the error it gives, I think the problem is in the file **kv.ts** on **line 45** in the regular expression `/(?<!\n)[,\n]/gi`.
