### ISSUE TITLE
Can't use multiple line val in env_vars

### ISSUE THREAD

**Issue by onel** [google-github-actions/actions-utils#139]
### TL;DR

I'm trying to deploy to cloud run and one of the `env_vars` has a value that is multi line, specifically it is a PEM key.
This seems to make the key not be used properly in cloud run UI.
The problem is with `GH_APP_PRIVATE_KEY`
Tried with with both `""` and without. 

In the google console UI the output looks like this
![image](https://github.com/user-attachments/assets/bd1bac37-9e94-4a57-b1f4-9821cd46dd95)

This might be a yaml question more than a deploy-cloudrun one.

### Action YAML

```yaml
- name: Deploy to Google Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2

        with:
          service: ${{ env.RUN_SERVICE }}
          image: ${{ env.GAR_LOCATION }}
          region: ${{ env.REGION }}

          env_vars: |-
            DEBUG='False'
            GH_APP_PRIVATE_KEY=${{ secrets.GH_APP_PRIVATE_KEY }}
```
